config/routes.rb
Rails.application.routes.draw do
  resources :ingredients, only: [:index]
  get '/ingredients/new/:recipe_id', to: 'ingredients#new', as: 'new_ingredient'
  post '/ingredients', to: 'ingredients#create'

  get '/recipes/home', to: 'recipes#home', as: 'recipe_home'
  get '/recipes', to: 'recipes#user_recipes', as: 'user_recipes'
  post '/recipes/completed/:id', to: 'recipes#completed', as: 'recipe_completed'
  get '/recipes/all', to: 'recipes#index', as: 'recipes'
  post '/recipes/all', to: 'recipes#create'
  resources :recipes, only: [:show, :new]
  

  resources :pantries, only: [:index, :create]  
  get '/users/:id/pantry', to: 'pantries#user_pantry', as: 'user_pantry'
  get '/users/:id/pantry/new', to: 'pantries#new', as: 'add_to_pantry'
  get '/users/:id/pantry/edit', to: 'users#edit', as: 'remove_from_pantry'
  patch '/users/:id', to: 'users#update'
  delete '/logout', to: 'users#delete'

  #resources :foods

  resources :users, only: [:index, :show, :new, :create]

  get '/login', to: 'sessions#new', as: "login"
  post '/login', to: 'sessions#create'
  #get '/users', to: 'users#index', as: 'users'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/pantry.rb
class Pantry < ApplicationRecord
  belongs_to :user
  belongs_to :food

  validates :food_id, uniqueness: {scope: :user_id, message: " already in your pantry!"}
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :ingredients
    has_many :foods, through: :ingredients

    validates :name, presence: true
    validates :name, uniqueness: true
    #validates :meal, inclusion: {in: %w(Breakfast Lunch Dinner Snack Dessert), message: "%{value} is not a valid meal type"}
    #validates :instructions, length: {minimum: 1 }

    def self.recipe_book
        recipes = {}
        Recipe.all.each do |recipe|
            food_names = recipe.foods.map { |food| food.name }
            recipes[recipe] = food_names
        end
        recipes
    end

    # def list_instructions
    #     #create a regex to split on. any number followed by a period
    #     #delimiter = /[1-20].\/
    #     self.instructions.match
    # end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :pantries
    has_many :foods, through: :pantries

    validates :username, presence: true
    validates :username, uniqueness: true
    validates :password, presence: true

    def find_recipes
      #get list of all foods that user has in pantry
      user_foods = self.foods.map { |food| food.name } 
    #   byebug
      #get recipes and their ingredients (foods)
      user_recipes = []
      Recipe.recipe_book.each do |recipe, ingredients_for_recipe| 
        # byebug
          if (ingredients_for_recipe - user_foods).empty?
            # byebug
              user_recipes << recipe
          end
      end
    #   byebug
      user_recipes
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :current_user
    
    def current_user
        @current_user = User.find_by(id: session[:user_id])
    end
    
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

    before_action :current_user
    
    def new
        @ingredient = Ingredient.new
        @recipe = Recipe.find(params[:recipe_id])
        @foods = Food.all
        @recipes = Recipe.all
    end

    def create
        @ingredient = Ingredient.create(ingredient_params)
        redirect_to recipe_path(@ingredient.recipe)
    end

    private 
    def ingredient_params
        params.require(:ingredient).permit(:recipe_id, :food_id, :amount)
    end
end

app/controllers/pantries_controller.rb
class PantriesController < ApplicationController

    def user_pantry
        @foods = current_user.foods
    end
    
    def new
        @pantry = Pantry.new
        @foods = Food.all
    end

    def create
        #add food id to user's pantry
        @pantry = Pantry.new(pantry_params)
        @pantry.user_id = current_user.id
        @pantry.save
        if @pantry.valid?
            redirect_to user_pantry_path(current_user)
        else
            flash[:errors] = @pantry.errors.full_messages
            redirect_to add_to_pantry_path(current_user)
        end
    end 

    

    private 
    def pantry_params
        params.require(:pantry).permit(:food_id)
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    
    def home 
    end

    def index
        @recipes = Recipe.all
    end

    def user_recipes 
        @user_recipes = @current_user.find_recipes
        # byebug
    end

    def show
        # byebug
        @recipe = Recipe.find(params[:id])
    end

    def new
        @recipe = Recipe.new
    end

    def create
        @recipe = Recipe.create(recipe_params)
        if @recipe.valid?
            redirect_to recipe_path(@recipe.id)
        else
            flash[:errors] = @recipe.errors.full_messages
            redirect_to new_recipe_path
        end
    end

    def completed
        @recipe = Recipe.find(params[:id])
        #byebug
        @recipe.update(completed: params[:button])
        redirect_to recipe_path(@recipe.id)
    end

    private
    def recipe_params
        params.require(:recipe).permit(:name, :meal, :cuisine, :instructions, :image_url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new 
    
    end 
  
    def create
      # find the user in the database by the name
      @user = User.find_by(username: params[:username])
      if @user
        session[:user_id] = user.id 
        redirect_to user_path(user)
      else
        flash[:errors] = "Incorrect username, please try again or sign up for an account"
        # byebug
        redirect_to login_path
      end

    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.create(params.require(:user).permit(:username, :password, :dietary_restriction))
        if @user.valid?
            session[:user_id] = @user.id
            redirect_to user_path(@user.id)
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
    end

    def show
        user = User.find(params[:id])
        session[:user_id] = user.id
    end
    
    def edit
        @user_foods = @current_user.foods
    end

    def update
        pantry_item = Pantry.find_by(food_id: params[:user][:foods], user_id: @current_user.id)
        # byebug
        @current_user.pantries.find(pantry_item.id).delete
        # @current_user.foods.delete(food_to_remove)
        redirect_to user_pantry_path(@current_user.id)
    end

    def delete
        session[:user_id] = nil
        redirect_to login_path
    end

    private
    def user_params
        params.require(:user).permit(:foods)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/pantries_helper.rb
module PantriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/new.html.erb
<div class="basic_design">
    <h1> Add Ingredients to <%= @recipe.name %></h1>

    <%= form_for @ingredient do |f| %>
        <p> <%= f.hidden_field(:recipe_id, value: @recipe.id) %> </p>
        <p> Ingredient: <%= f.collection_select :food_id, @foods, :id, :name %> </p>
        <p> Amount: <%= f.text_field :amount %> </p>
        <%= f.submit "Add ingredient to recipe" %>
    <% end %>

 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>What's in Your Pantry</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header"> 
      <nav class = "left">
        <h3> What's in your Pantry? </h3>
      </nav>
      <nav class="right">
        <% if @current_user %>
          <%= link_to "View your profile", user_path(@current_user)%>🍲
          <%= link_to "Log out", '/logout', method: :delete %>
        <% else %>
          <h3> <%= link_to "Sign Up", new_user_path %> </h3>
          <h3> <%= link_to "Log in", login_path %> </h3>  
        <% end %>
      </nav>

    </div>

    <%= yield %>
  </body>
</html>

app/views/pantries/new.html.erb
<div class='basic_design'>
   <h1> Add food to pantry: </h1>

   <% if flash[:errors] %>
        <% flash[:errors].each do |error|%>
            <p>Error: <%= error %></p>
        <% end %>
    <% end %>
    
   <%= form_for @pantry do |f| %>
      <p> Name of food: <%= f.collection_select :food_id, @foods.sort, :id, :name %> </p>
      <%= f.submit "Add food" %>
   <% end %>
</div>

app/views/pantries/user_pantry.html.erb
<div class='basic_design'>
    <h1> <%= @current_user.username %>'s Pantry </h1>
    <span>
        <% @foods.sort.each do |food| %>
            <p><%= food.name %></p>
        <% end %>
    </span>
    <br></br>    
    <%= link_to "Add Food to Pantry", add_to_pantry_path(@current_user) %>
    <%= link_to "Remove Food from Pantry", remove_from_pantry_path %>
    <%= link_to "Back to my profile", user_path(@current_user.id) %>

</div>

app/views/recipes/home.html.erb
<div class='basic_design'>
    <h1> Recipe Home Page </h1>

    <nav class='recipe_right'>
        <p> <%= link_to "Available Recipes", user_recipes_path %> </p>
        <p> <%= link_to "View All Recipes", recipes_path %> </p>
        <p> <%= link_to "Create New Recipe", new_recipe_path %> </p>
        <p><%= link_to "Back to my profile", user_path(@current_user.id) %></p>
    </nav>
</div>

app/views/recipes/index.html.erb
<div class='basic_design'>
    <h1> All Recipes </h1>

    <% @recipes.each do |recipe| %>
        <p><%=link_to recipe["strMeal"], recipe_path(recipe["idMeal"])%> | Cuisine: <%=recipe["strArea"]%> | Meal: <%=recipe["strCategory"]%></p>
    <% end %>    

    <p><%= link_to "Back to recipes home", recipe_home_path %></p>
    <p><%= link_to "Back to my profile", user_path(@current_user.id) %></p>
</div>

app/views/recipes/new.html.erb
<div class='basic_design'>
    <h1> Create a New Recipe </h1>

    <% if flash[:errors] %>
        <% flash[:errors].each do |error|%>
            <p>Error: <%= error %></p>
        <% end %>
    <% end %>

    <%= form_for @recipe do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :meal %>
        <%= f.text_field :meal %>
        <%= f.label :cuisine %>
        <%= f.text_field :cuisine %>
        <%= f.label :instructions %>
        <%= f.text_field :instructions %>
        <%= f.label :image_url %>
        <%= f.text_field :image_url %>
        <%= f.submit %>
    <% end %>

</div>

app/views/recipes/show.html.erb
<div class='basic_design'>
    <h1> Recipe for <%= @recipe.name %></h1>
    <div class='recipe'>
        <div class='recipe_ingredients'>
            <h3> Ingredients </h3>
            <% @recipe.ingredients.each do |ingredient|%>
                <p><%= ingredient.amount %>  <i><%= ingredient.food.name %></i> </p>
            <% end %> 

            <% if @recipe.completed && @recipe.completed == true %>
                <%= form_with url: recipe_completed_path(@recipe.id) do |form| %>
                    <%= form.button 'Edit Ingredients List', value: false %>
                <% end %>
            <% else %>
                <p><%= link_to "Add ingredients", new_ingredient_path(@recipe) %></p> 
                <%= form_with url: recipe_completed_path(@recipe.id) do |form| %>
                    <%= form.button 'Mark Ingredients List Complete', value: true %>
                <% end %>
            <% end %>  
        </div>
        <div class='recipe_instructions'>
            <h3> Instructions </h3>
            <p><%= @recipe.instructions %> </p>
        </div>
        <div class="recipe_img">
            <%= image_tag(@recipe.image_url, :alt => "Image of #{@recipe.name}") %>
        </div>
    </div>            
    <nav class = 'recipe_right'>
            <p><%= link_to "Back to recipes home", recipe_home_path %></p>
    </nav>

</div>

app/views/recipes/user_recipes.html.erb
<div class = 'basic_design'>
    <h1> Recipes Based on your Pantry </h1>
    <% @user_recipes.each do |recipe|%>
        <p><%=link_to recipe.name, recipe_path(recipe.id)%> | Cuisine: <%=recipe.cuisine%> | Meal: <%=recipe.meal%></p>
    <% end %>
    <nav class = 'recipe_right'>
        <p><%= link_to "Back to recipes home", recipe_home_path %></p>
        <p><%= link_to "Back to my profile", user_path(@current_user.id) %></p>
    </nav>
</div>

app/views/users/edit.html.erb
<h1> Remove food from pantry: </h1>

<%= form_for @current_user do |f| %>
   <p> Name of food: <%= f.collection_select :foods, @user_foods.sort, :id, :name %> </p>
   <%= f.submit "Remove food" %>
<% end %>

app/views/users/new.html.erb
<div class='basic_design'>
    <h1> Create your Profile </h1>

    <% if flash[:errors] %>
        <% flash[:errors].each do |error|%>
            <p>Error: <%= error %></p>
        <% end %>
    <% end %>

    <%= form_for @user do |f| %>
        <p>Enter username: <%= f.text_field :username %></p>
        <p>Enter password: <%= f.password_field :password %></p>
        <p>Enter any dietary restrictions you may have: <%= f.text_field :dietary_restriction %></p>
        <%= f.submit "Create profile" %>
    <% end %>
</div>

app/views/users/show.html.erb
<div class='basic_design'>
    <h1> Welcome <%= @current_user.username %>!</h1>

    <p> Dietary Restrictions: <%= @current_user.dietary_restriction %> </p>
    <%= link_to "View Pantry", user_pantry_path(@current_user.id) %>
    <%= link_to "Find Recipes", recipe_home_path %> 

</div>    